"""Initial migration

Revision ID: 46e13fab3584
Revises: 
Create Date: 2025-01-14 16:05:41.101894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46e13fab3584'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stk_push', sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', 'CANCELLED', 'TIMEOUT', name='mpesa_status_enum'), nullable=False))
    op.add_column('stk_push', sa.Column('result_code', sa.String(), nullable=True))
    op.add_column('stk_push', sa.Column('result_desc', sa.String(), nullable=True))
    op.drop_constraint('stk_push_transaction_id_key', 'stk_push', type_='unique')
    op.drop_column('stk_push', 'transaction_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stk_push', sa.Column('transaction_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint('stk_push_transaction_id_key', 'stk_push', ['transaction_id'])
    op.drop_column('stk_push', 'result_desc')
    op.drop_column('stk_push', 'result_code')
    op.drop_column('stk_push', 'status')
    # ### end Alembic commands ###
