name: Build and Deploy FastAPI App

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build and push image
        run: |
          docker build -t lettting/f-api-oneshop .
          docker push lettting/f-api-oneshop

      - name: Deploy to server
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_DEPLOY_KEY }}
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "
            cd ~/oneshop &&
            docker-compose -f oneshop.yml down --remove-orphans &&
            docker system prune -af &&
            docker-compose -f oneshop.yml pull &&
            docker-compose -f oneshop.yml up -d
          "
