name: Deploy FastAPI App

on:
  push:
    branches: [ main ]  # or your main deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy FastAPI files to server
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no" harmonyapi/ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/home/${{ secrets.SERVER_USER }}/harmonyapi/

      - name: Deploy with Docker Compose
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "
            cd ~/harmonyapi &&
            docker-compose -f harmony.yml down &&
            docker-compose -f harmony.yml pull &&
            docker-compose -f harmony.yml up -d --build
          "

